version: 2.1

commands:
    restore_installed_repo:
        steps:
            - checkout
            - restore_cache:
                  key: deps-v1-{{ checksum "package-lock.json" }}

    restore_workspace:
        steps:
            - attach_workspace:
                  at: .

executors:
    node:
        docker:
            - image: circleci/node:11
        working_directory: ~/excel-comparatpr

jobs:
    dependencies-install:
        executor: node

        steps:
            - restore_installed_repo
            - run:
                  name: Install dependencies
                  command: if [[ ! -d node_modules ]]; then npm ci; fi
            - save_cache:
                  key: deps-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
                      - ~/.cache
                      - ~/.npm

    build:
        executor: node

        steps:
            - restore_installed_repo
            - run: npm run build
            - persist_to_workspace:
                  root: .
                  paths:
                      - dist

    deploy:
        executor: node

        steps:
            - restore_installed_repo
            - attach_workspace:
                  at: .
            - run: npm run firebase -- use excel-comparator
            - run: npm run firebase -- deploy --force --non-interactive -m $CIRCLE_SHA1 --token "$FIREBASE_TOKEN"

workflows:
    version: 2
    default_workflow:
        jobs:
            - dependencies-install
            - build:
                  requires:
                      - dependencies-install
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
